"""Region mapping seed data for the persistence schema."""

import sqlite3


def insert_default_region_mapping(conn: sqlite3.Connection) -> None:
    """Insert default nationality -> region mapping."""
    # Nordic countries
    nordic = [
        "Denmark",
        "Norway",
        "Sweden",
        "Iceland",
        "Finland",
        "Faroe Islands",
    ]
    european = [
        "Germany",
        "France",
        "Italy",
        "Spain",
        "Portugal",
        "Netherlands",
        "Belgium",
        "Switzerland",
        "Austria",
        "Poland",
        "Czech",
        "Slovakia",
        "Hungary",
        "Romania",
        "Bulgaria",
        "Greece",
        "Croatia",
        "Serbia",
        "Slovenia",
        "Lithuania",
        "Latvia",
        "Estonia",
        "United Kingdom",
        "Ireland",
        "Scotland",
        "Wales",
        "England",
        "Russia",
        "Ukraine",
        "Belarus",
        "Moldova",
        "Albania",
        "Bosnia",
        "Montenegro",
        "Macedonia",
        "Kosovo",
    ]
    # Middle Eastern
    middle_eastern = [
        "Egypt",
        "Turkey",
        "Iran",
        "Iraq",
        "Syria",
        "Jordan",
        "Lebanon",
        "Israel",
        "Palestine",
        "Saudi Arabia",
        "Yemen",
        "Oman",
        "United Arab Emirates",
        "Qatar",
        "Kuwait",
        "Bahrain",
        "Afghanistan",
        "Pakistan",
    ]
    # Asian
    asian = [
        "China",
        "Japan",
        "South Korea",
        "North Korea",
        "India",
        "Bangladesh",
        "Pakistan",
        "Sri Lanka",
        "Nepal",
        "Bhutan",
        "Myanmar",
        "Thailand",
        "Vietnam",
        "Cambodia",
        "Laos",
        "Philippines",
        "Indonesia",
        "Malaysia",
        "Singapore",
        "Taiwan",
        "Hong Kong",
        "Mongolia",
    ]
    # African
    african = [
        "Nigeria",
        "Ethiopia",
        "Egypt",
        "South Africa",
        "Kenya",
        "Tanzania",
        "Uganda",
        "Ghana",
        "Morocco",
        "Algeria",
        "Sudan",
        "Mozambique",
        "Madagascar",
        "Cameroon",
        "Ivory Coast",
        "Niger",
        "Burkina Faso",
        "Mali",
        "Senegal",
        "Zambia",
        "Zimbabwe",
        "Tunisia",
        "Libya",
    ]
    # American
    american = [
        "United States",
        "Canada",
        "Mexico",
        "Brazil",
        "Argentina",
        "Chile",
        "Colombia",
        "Peru",
        "Venezuela",
        "Ecuador",
        "Bolivia",
        "Paraguay",
        "Uruguay",
        "Cuba",
        "Dominican Republic",
        "Puerto Rico",
        "Jamaica",
        "Haiti",
        "Trinidad and Tobago",
        "Bahamas",
        "Barbados",
        "Guyana",
        "Suriname",
        "Belize",
        "Costa Rica",
        "Panama",
        "Nicaragua",
        "Honduras",
        "El Salvador",
        "Guatemala",
    ]
    # Oceanian
    oceanian = [
        "Australia",
        "New Zealand",
        "Fiji",
        "Papua New Guinea",
        "Samoa",
        "Tonga",
        "Vanuatu",
        "Solomon Islands",
        "Micronesia",
        "Palau",
        "Marshall Islands",
        "Kiribati",
        "Tuvalu",
        "Nauru",
    ]

    mappings = [
        *[("Nordic", country) for country in nordic],
        *[("European", country) for country in european],
        *[("Middle Eastern", country) for country in middle_eastern],
        *[("Asian", country) for country in asian],
        *[("African", country) for country in african],
        *[("American", country) for country in american],
        *[("Oceanian", country) for country in oceanian],
    ]

    conn.executemany(
        "INSERT OR IGNORE INTO region_mapping (region, nationality) VALUES (?, ?)",
        mappings,
    )
