"""Region mapping seed data for the persistence schema."""

import sqlite3
from collections.abc import Mapping

DEFAULT_REGION_COUNTRIES: Mapping[str, tuple[str, ...]] = {
    "Nordic": (
        "Denmark",
        "Norway",
        "Sweden",
        "Iceland",
        "Finland",
        "Faroe Islands",
    ),
    "European": (
        "Germany",
        "France",
        "Italy",
        "Spain",
        "Portugal",
        "Netherlands",
        "Belgium",
        "Switzerland",
        "Austria",
        "Poland",
        "Czech",
        "Slovakia",
        "Hungary",
        "Romania",
        "Bulgaria",
        "Greece",
        "Croatia",
        "Serbia",
        "Slovenia",
        "Lithuania",
        "Latvia",
        "Estonia",
        "United Kingdom",
        "Ireland",
        "Scotland",
        "Wales",
        "England",
        "Russia",
        "Ukraine",
        "Belarus",
        "Moldova",
        "Albania",
        "Bosnia",
        "Montenegro",
        "Macedonia",
        "Kosovo",
    ),
    "Middle Eastern": (
        "Egypt",
        "Turkey",
        "Iran",
        "Iraq",
        "Syria",
        "Jordan",
        "Lebanon",
        "Israel",
        "Palestine",
        "Saudi Arabia",
        "Yemen",
        "Oman",
        "United Arab Emirates",
        "Qatar",
        "Kuwait",
        "Bahrain",
        "Afghanistan",
        "Pakistan",
    ),
    "Asian": (
        "China",
        "Japan",
        "South Korea",
        "North Korea",
        "India",
        "Bangladesh",
        "Pakistan",
        "Sri Lanka",
        "Nepal",
        "Bhutan",
        "Myanmar",
        "Thailand",
        "Vietnam",
        "Cambodia",
        "Laos",
        "Philippines",
        "Indonesia",
        "Malaysia",
        "Singapore",
        "Taiwan",
        "Hong Kong",
        "Mongolia",
    ),
    "African": (
        "Nigeria",
        "Ethiopia",
        "Egypt",
        "South Africa",
        "Kenya",
        "Tanzania",
        "Uganda",
        "Ghana",
        "Morocco",
        "Algeria",
        "Sudan",
        "Mozambique",
        "Madagascar",
        "Cameroon",
        "Ivory Coast",
        "Niger",
        "Burkina Faso",
        "Mali",
        "Senegal",
        "Zambia",
        "Zimbabwe",
        "Tunisia",
        "Libya",
    ),
    "American": (
        "United States",
        "Canada",
        "Mexico",
        "Brazil",
        "Argentina",
        "Chile",
        "Colombia",
        "Peru",
        "Venezuela",
        "Ecuador",
        "Bolivia",
        "Paraguay",
        "Uruguay",
        "Cuba",
        "Dominican Republic",
        "Puerto Rico",
        "Jamaica",
        "Haiti",
        "Trinidad and Tobago",
        "Bahamas",
        "Barbados",
        "Guyana",
        "Suriname",
        "Belize",
        "Costa Rica",
        "Panama",
        "Nicaragua",
        "Honduras",
        "El Salvador",
        "Guatemala",
    ),
    "Oceanian": (
        "Australia",
        "New Zealand",
        "Fiji",
        "Papua New Guinea",
        "Samoa",
        "Tonga",
        "Vanuatu",
        "Solomon Islands",
        "Micronesia",
        "Palau",
        "Marshall Islands",
        "Kiribati",
        "Tuvalu",
        "Nauru",
    ),
}


def insert_default_region_mapping(conn: sqlite3.Connection) -> None:
    """Insert default nationality -> region mapping."""
    mappings = [(region, country) for region, countries in DEFAULT_REGION_COUNTRIES.items() for country in countries]

    conn.executemany(
        "INSERT OR IGNORE INTO region_mapping (region, nationality) VALUES (?, ?)",
        mappings,
    )
